apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bootit
  labels:
    app: bootit
  annotations:
    flux.weave.works/automated: "true"
spec:
  replicas: 2
  progressDeadlineSeconds: 180
  selector:
    matchLabels:
      app: bootit
  template:
    metadata:
      labels:
        app: bootit
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: bootit
        image: ollireg.azurecr.io/bootit/bootit:1.0.28
        args: [
          "--spring.profiles.active=dev"
        ]
        ports:
        - containerPort: 8002
          name: rest
        - containerPort: 8003
          name: actuator
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "150M"
          limits:
            # Relies on image defining -XX:+UnlockExperimentalVMOptions and -XX:+UseCGroupMemoryLimitForHeap
            # Too aggressive for prod?
            memory: "300M"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8003
          # Initial delay should be large enough to allow the app to successfully start
          initialDelaySeconds: 120
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 5
        # Readiness probe allows Kubernetes to know when to direct traffic to the replica.
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 2
      imagePullSecrets:
      - name: regcred
