apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bootit
  labels:
    app: bootit
  annotations:
    flux.weave.works/automated: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bootit
  template:
    metadata:
      labels:
        app: bootit
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: bootit
        image: ollireg.azurecr.io/bootit/bootit:1.0.7
        args: [
          "--spring.profiles.active=dev"
        ]
        ports:
        - containerPort: 8002
          name: rest
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8002
          # Initial delay should be large enough to allow the app to successfully start
          initialDelaySeconds: 120
          periodSeconds: 2
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8002
          initialDelaySeconds: 2
          periodSeconds: 2
      imagePullSecrets:
      - name: regcred
