apiVersion: v1
kind: Service
metadata:
  name: {{ template "bootit.cache" . }}
  labels:
    app: {{ template "bootit.name" . }}
    chart: {{ template "bootit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: cache
spec:
  selector:
    app: {{ template "bootit.name" . }}
    release: {{ .Release.Name }}
    component: cache
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http