apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "bootit.cache" . }}
  labels:
    app: {{ template "bootit.name" . }}
    chart: {{ template "bootit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "bootit.name" . }}
      release: {{ .Release.Name }}
      component: cache
  template:
    metadata:
      labels:
        app: {{ template "bootit.name" . }}
        release: {{ .Release.Name }}
        component: cache
    spec:
      containers:
      - name: master
        image: k8s.gcr.io/redis:e2e
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
          name: http
          protocol: TCP