apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "bootit.fullname" . }}
  labels:
    app: {{ template "bootit.name" . }}
    chart: {{ template "bootit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  progressDeadlineSeconds: {{ .Values.app.progressDeadlineSeconds }}
  selector:
    matchLabels:
      app: {{ template "bootit.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bootit.name" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.app.terminationGracePeriodSeconds }}
      imagePullSecrets:
        - name: {{ template "imagePullSecret.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [
            "{{ "--spring.profiles.active" }}={{ .Values.app.springProfiles }}"
          ]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8002
              name: http
              protocol: TCP
            - containerPort: 8003
              name: actuator
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: actuator
            # Initial delay should be large enough to allow the app to successfully start
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
          # Readiness probe allows Kubernetes to know when to direct traffic to the replica.
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: actuator
            initialDelaySeconds: 5
            periodSeconds: 2
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
