{{- if .Values.image.credentials.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "imagePullSecret.fullname" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}