---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elk
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  filebeat.yml: |-
    filebeat.config:
      prospectors:
        # Mounted `filebeat-prospectors` configmap:
        path: ${path.config}/prospectors.d/*.yml
        # Reload prospectors configs as they change:
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: false

    filebeat.autodiscover:
      providers:
      - type: kubernetes
        templates:
        - condition:
            not:
              or:
              - contains:
                 kubernetes.namespace: elk
              - contains:
                 kubernetes.namespace: kube-system
          config:
          - type: docker
            containers.ids:
            - "${data.kubernetes.container.id}"
            processors:
            - add_kubernetes_metadata:
                in_cluster: true

    processors:
      - add_cloud_metadata:

    #output.console:
    #  pretty: true

    output.logstash:
     hosts: ["logstash:5044"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-prospectors
  namespace: elk
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  kubernetes.yml: |-
    # - type: log
    #   paths:
    #   - /var/log/spring.log