apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk
  labels:
    app: logstash
data:
  pipeline.conf: |-
    input {
      beats {
        port => 5044
      }
    }

    filter {
      if [kubernetes.namespace] == "elk" {
        drop {}
      }
      if [kubernetes.namespace] == "kube-system" {
        drop {}
      }
    }

    output {
      #elasticsearch { hosts => "elasticsearch:9200" }
      stdout {}
    }